version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  tareas:
    build: ./task
    ports:
      - "5001:5000"
    depends_on:
      - redis
  usuario:
    build: ./user
    ports:
      - "5002:5000"
    depends_on:
      - redis
  notificacion:
    build: ./notification
    ports:
      - "5003:5000"
    depends_on:
      - redis
