version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  usuario:
    build: ./usuario
    ports:
      - "5000:5000"
    depends_on:
      - redis

  tareas:
    build: ./tareas
    ports:
      - "5001:5001"
    depends_on:
      - redis

  notificacion:
    build: ./notificacion
    ports:
      - "5002:5002"
    depends_on:
      - redis
